### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by cortegedusage** [Saiyato/volumio-pydpiper-plugin#1]
Awsome,
This is indeed the best script to display on a LCD screen.
Did you change anything in the pages section? 
Of did you left it as it was?

Cheers,
Dennis

**Comment by Saiyato** [comment]
I changed some files suffixed with volumio, but feel free to edit them yourself ;)
These changed files will only be called when you use 'local directory' as your mounting point.

I will be updating the unit file and a start script in a bit, so expect a new version soon.
