### ISSUE TITLE
problem with unzip file

### ISSUE THREAD

**Issue by rafalkarvolumio** [Saiyato/volumio-pydpiper-plugin#3]
Hi
I have problem with unzip file.
Can you help me?
I have rpi3b+ with volumio 2.411

**Information about the problem**
volumio@volumio:~$ miniunzip volumio-pydpiper-plugin.zip
MiniUnz 1.01b, demo of zLib + Unz package written by Gilles Vollant
more info at http://www.winimage.com/zLibDll/unzip.html

Cannot open volumio-pydpiper-plugin.zip or volumio-pydpiper-plugin.zip.zip

_

**Comment by Saiyato** [comment]
What did you do exactly? Can you post all consecutive commands you typed?
